name: Continuous release

on: [push, pull_request]

env:
  APPIMAGE_EXTRACT_AND_RUN: 1

jobs:
  appimage-x86_64:
    name: AppImage x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build AppImage
        run: |
          export ARCH=aarch64 APPIMAGE_EXTRACT_AND_RUN=1
          bash -xe build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage x86_64
          path: ReText*.AppImage*

# deactivated until there's a proper solution avoiding the need for building our own PyQt5
#  appimage-i386:
#    name: AppImage i386 (cross)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: |
#          sudo dpkg --add-architecture i386
#          sudo apt-get update
#          sudo apt-get install -y --no-install-recommends \
#              libc6:i386 libstdc++6:i386 libffi6:i386 libgmp10:i386 zlib1g:i386 libfuse2:i386 \
#              gcc-multilib g++-multilib wget
#      - name: Build AppImage
#        run: |
#          export ARCH=i386 APPIMAGE_EXTRACT_AND_RUN=1 CI=1
#          export CC="gcc -m32" CXX="g++ -m32" LDSHARED="$CC -pthread -shared" DISTUTILS_DEBUG=1
#          bash -xe build.sh
#      - name: Archive artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: AppImage i386
#          path: ReText*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - appimage-x86_64
#      - appimage-i386
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        uses: marvinpinto/action-automatic-releases@latest
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "continuous"
          prerelease: true
          title: "Continuous build"
          files: |
            **/ReText*.AppImage*

